## R Markdown utils
#
# 1. hooks
# 2. table generation
# 3.

#' Show the download links of figures when multiple devices are used
#'
#' When use multiple devices, i.e., pdf, svg, ppt, multiple figures will
#' be generated after rendering. This function automatically add the links
#' to these files in figure captions.
#'
#' @param ... figure caption
#' @param PPT whether output PPT link
#' @param PDF whether output PDF link
#'
#' @return a markdown format string
#' @export
figure_caption_link <- function(..., PPT = TRUE, PDF = TRUE){
  x <- paste0(...)
  if (PPT) x <- paste0(x," [ppt](", knitr::fig_path(".pptx"),"),")
  if (PDF) x <- paste0(x, " [pdf](", knitr::fig_path(".pdf"),")")
  return(x)
}



#############################
# 2. Table Generation
#############################


#' A table generated by `DT::datatable()` with button to export data
#'
#'
#'
#' @param df data frame
#'
#' @return a datatable html widget
#' @export
#'
#' @examples DT_table(head(iris))
DT_table = function(df){
  df %>%
    DT::datatable(extensions = c("Buttons"),
                  colnames = var2header(colnames(df)),
                  rownames = FALSE,
                  options = list(
                    dom = 'Bfrtip',
                    scrollX = TRUE,
                    buttons = list(
                      'pageLength',
                      list(extend="excel",
                           filename=paste0(substitute(df)),
                           header=TRUE)
                    )
                  ))
}


#' A table generated by kableExtra
#'
#' Can be safely used in PDF document.
#'
#' @param tibble a tibble
#'
#' @return a table
#' @export
#'
#' @examples kable_classic(head(iris))
kable_classic = function(tibble){
  tibble %>%
    knitr::kable(digits = 3, col.names = var2header(colnames(tibble))) %>%
    kableExtra::kable_classic(font_size = 10, full_width = FALSE)
}


#' Remove specific connector in string
#'
#' 变量名中间常用下划线连接单词，而这在显示的时候是多余。
#' 这个函数可以去掉单词间的下划线。
#'
#' @param x string
#'
#' @return a string
#' @export
var2header = function(x){
  gsub("_"," ",x)
}
